package com.kuaima.addressmanager.dao;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADDRESS.
 */
public class Address implements Serializable{

    private Long id;
    private String username;
    private String mobileNo;
    private String area;
    private String street;
    private String detail;
    private Boolean isDefault;

    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    public Address(Long id, String username, String mobileNo, String area, String street, String detail, Boolean isDefault) {
        this.id = id;
        this.username = username;
        this.mobileNo = mobileNo;
        this.area = area;
        this.street = street;
        this.detail = detail;
        this.isDefault = isDefault;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Boolean getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

}
